### ISSUE TITLE
Directional problems with Hebrew typing on source sheets

### ISSUE THREAD

**Issue by SaraWolkenfeld** [Sefaria/Sefaria-Project#119]
From one of our partner institutions - it is still the case that if you want to type (or copy and paste) in Hebrew on to a source sheet, the direction doesn't totally change to right-to-left, such that punctuation often winds up in the wrong place.

**Comment by pzp1997** [comment]
Not sure if we're talking about the same issue, as this issue is over a year and a half old and pre-s2, but it might have been fixed by #229. @SaraWolkenfeld or @EliezerIsrael Could you check if this is still a problem? If it is and you can give me some steps to reproduce it, I'd be glad to take a shot at fixing it.
