### ISSUE TITLE
No way back from Yiddish translation

### ISSUE THREAD

**Issue by dsadinoff** [Sefaria/Sefaria-Project#1628]
On the desktop version of the web sefaria

If I select the Yiddish translation of the Torah  - Yehoyesh's Yiddish Tanakh Translation [yi]
1) the Masoretic Hebrew text is replaced with the Yiddish, which is a bit surprising.  I would have expected for the yiddish to go in the "translation" slot where the various English or French etc translations go

Perhaps related, and more importantly, 

2) there's no way back.  Once I select the Yiddish, there's no obvious way to turn it off and get the base text back.

e.g. in the screenshot attached, where do I click to turn off the yiddish?
![Screenshot 2023-09-07 095658](https://github.com/Sefaria/Sefaria-Project/assets/287416/a015e2a4-d962-4b19-a13e-7fb5748362b7)

**Comment by edamboritz** [comment]
Hi! 
Thank you for the feedback! 
The fact that Yiddish appears in place of the Hebrew is a limitation of our current software. 
You'll be happy to know we are already in the midst of working on a overhaul that will fix exactly that, so you can see Yiddish side by side with the Hebrew!  

In the meantime, you can get the Hebrew back by going to "About this Text" at the top of the connections panel, rather than "Translations", where you can scroll down and see a list of "Source Versions" that you can click to put in the main panel.  
![image](https://github.com/Sefaria/Sefaria-Project/assets/7577402/caa4d67b-abe4-4c5b-acc0-fd98846a1b2d)
![image](https://github.com/Sefaria/Sefaria-Project/assets/7577402/5d8c22a8-c13b-4217-8b93-520d474c22d2)
