### ISSUE TITLE
Problem with Hebrew fonts on source sheet

### ISSUE THREAD

**Issue by CantorEvan** [Sefaria/Sefaria-Project#320]
I created a source sheet on my home computer using the text of the hatarah in Hebrew and English.  But when I got to the synagogue's computer, the Hebrew font was all messed up (it looked great at home).  Is there a font that I'm missing on the synagogue's computer?  If so, how do I download it?

Evan

**Comment by pzp1997** [comment]
In what way was the font messed up?  Were some of the letters not showing at all? Were they showing but they just looked different than how they looked on your home computer? Were the letters out of order so that the words were indecipherable? Some weird combination of any of the above, or something else entirely? It would be helpful if you could post a screenshot or picture of how the font was displayed on the synagogue's computer. If you do not have one, a short description of how the font was being displayed would make it easier to pinpoint and fix the problem.

**Comment by CantorEvan** [comment]
Here's how it looks:

![image](https://cloud.githubusercontent.com/assets/27491719/25042784/516022ea-2123-11e7-808c-c112201f23aa.png)

Thanks for your help!

**Comment by pzp1997** [comment]
Okay, so it seems that the cantillation marks are not showing correctly and some of the letters are incorrectly sized.  I would like to determine if this is a system-wide issue or just isolated to a particular browser version. From that screenshot, it looks like the synagogue's computer is running Windows 7 and you are accessing Sefaria with Google Chrome. Can you confirm this and give the version of Chrome you are using (you can find that information by going to chrome://version/ in the address bar)? Also, would you mind trying to open the source sheet in a different browser, say Firefox, to see if the problem exists there as well?

**Comment by CantorEvan** [comment]
I don't have firefox on the computer here, so I'll have to download it.  In the meantime, the version of Chrome is the latest: 57.0.2987.133, and I used Chrome at home with no problem.  That's why I think that for whatever reason I'm missing a font on my computer.

**Comment by CantorEvan** [comment]
I downloaded Firefox, and this is what I got.
![image](https://cloud.githubusercontent.com/assets/27491719/25043489/2414581e-2129-11e7-9b68-639d3202070b.png)
Although it looks different, as you see, it's still not "right".  So apparently my computer here at the shul doesn't know what to do with the font.  Any ideas?

**Comment by pzp1997** [comment]
This problem looks eerily like issue #183. Perhaps someone who helped to resolve that issue, @edamboritz or @blockspeiser, would be better equipped to deal with this one.

One interesting thing that I noticed is that the source sheets use a different Hebrew font than the main site. The main site seems to use mostly Taamey Frank and Open Sans Hebrew, while the source sheets use Times New Roman by default. If the main site is being displayed correctly for you (try opening https://www.sefaria.org/Song_of_Songs.1.1?lang=bi), then I would guess that the problem is with the font being used for source sheets. Otherwise, the issue is probably with how your OS/browser displays cantillation marks.

**Comment by blockspeiser** [comment]
When we've seen this it has been an issue of an older version of Times New Roman installed on your computer. 

Here's some info about updating files:
https://groups.google.com/forum/#!msg/sefaria/cVGp6s2aF9w/s-mlbNJtBEMJ

**Comment by CantorEvan** [comment]
Hi Brett,

Indeed it was the Times New Roman fonts causing the issue.  The link you
sent, directing me to download the newer version of the font, solved the
problem. To test it, I just printed a file here at the synagogue and it
looks perfect.  Thanks so much for your help!

From a very happy cantor,

Evan


Cantor Evan Cohen    החזן אבן כהן
          Kehilat Har-El           קהילת הר-אל
  Jerusalem                        ירושלים
www.kharel.org.il
www.facebook.com/kehilat.har.el
cantorevan@gmail.com
+972-54-4742-314
Graduate of TACI - The Tel Aviv Cantorial Institute
בוגר מכון ת"א לחזנות
Come celebrate an unforgettable bar/bat mitzvah with Kehilat Har-El at
"Ezrat Yisrael" (Robinson's Arch):
http://www.youtube.com/watch?v=f_v0-b_fUZo

On Fri, Apr 14, 2017 at 8:31 PM, Brett Lockspeiser <notifications@github.com
