### ISSUE TITLE
Scrolling through works is broken with Javascript disabled

### ISSUE THREAD

**Issue by YairRand** [Sefaria/Sefaria-Project#342]
(This is probably fairly low-priority, but...)

When scrolling through a work with Javascript disabled, scrolling only works for a short distance before the bottom of the page shows the text "Loading..." without continuing. I recommend using some CSS to show a link to the following section instead of the loading box for users without JS.

(Other issues with disabled JS: Search box doesn't work, commentaries are inaccessible, the various tabs in the tables of contents are broken, and the "Aא" button is visible despite not doing anything.)

**Comment by rneiss** [comment]
This is the expected behavior. Texts are loaded a section at a time. Additional sections are added via lazy load when the javascript code recognizes the browser position getting toward the bottom of that section. We do not anticipate changing this behavior.

If you wish to brows without javascript, additional sections can  be selected via the text table of content page which can be accessed by clicking on the title of the section at the top of the panel.

**Comment by YairRand** [comment]
To to avoid confusion for those browsing without JS, it might be helpful to add `<noscript><style>.loadingMessage{display:none;}</style></noscript>` or similar somewhere.

(Opening a separate issue for the search box issue.)

**Comment by nsantacruz** [comment]
There are many aspects of our site which won't work without Javascript. In fact, with use React, so the entire HTML is generated through Javascript. I think a more appropriate suggestion would be to display a banner at the top of the site if Javascript is disabled informing users that the site will not work without Javascript. This is common practice.

**Comment by YairRand** [comment]
> In fact, we use React, so the entire HTML is generated through Javascript.

? No, the HTML is not generated through client-side Javascript. The pages are rendering fine without JS, they just don't respond to certain actions as they normally would. And frankly, given that the site is mainly for reading static text, lack of interactivity doesn't seem like it really matter all that much.
