### ISSUE TITLE
Logging at Hebrew site doesn't work

### ISSUE THREAD

**Issue by chaimkut** [Sefaria/Sefaria-Project#399]
If I open sefaria.org from a Chrome Incognito Window, sefaria recognizes that I am logging in from an Israeli IP and opens www.sefaria.org.il . I click on התחבר , provide my login details but all that happens is that I am moved back to www.sefaria.org (English) without being logged into my account (I only see the usual "Sign up" and "Log in" buttons on the top right, and no username icon). If I log in using this usual (www.sefaria.org) "Log in", then I successfully connect to my account without problem. I assume this has something to do with the fact that my account was opened on www.sefaria.org long ago and perhaps those login credentials don't work on www.sefaria.org.il....? At least from a UX perspective, the flow should probably be tweaked...

**Comment by rneiss** [comment]
This is actually the expected behavior -- We attach a cookie to your user account to save interface language preference, which somehow here got stuck on the wrong one. 

That said -- You can change by navigating to: https://www.sefaria.org/interface/hebrew when logged in. This link is also available in the page footer by clicking on `עברית` down at the bottom under `SITE LANGUAGE`

You can also change it in your account settings page which is accessible by clicking on the person icon in the header bar and then clicking on settings, or navigable directly at: https://www.sefaria.org/settings/account

I'm going to close this, but feel free to reopen if you have any additional questions or problems.

**Comment by chaimkut** [comment]
The only thing I would suggest is to allow the initial login from www.sefaria.org.il to succeed, even if you do choose to then forward to www.sefaria.org. But having the user correctly enter username, password and then magically end up at www.sefaria.org without being logged in is confusing. The user doesn't know if their login info is wrong, should they bother trying again, etc.
