### ISSUE TITLE
Chrome OS - unable to search texts offline

### ISSUE THREAD

**Issue by brnvogel** [Sefaria/Sefaria-Project#466]
I am currently using Sefaria on a Chromebook.
I have downloaded the complete library.
When running offline and attempting to search text, I get a message requesting me to go online.
Running release 4.1.12
Previous release with the single library allowed me to search texts offline.
Searching online works OK

**Comment by brnvogel** [comment]
I am now running release 5.2.6
When working offline, I am no longer getting a request to go online (Progress ?)
However the Search still does not work - program hangs.
In the Filters tab there is the message "Loading Filters ..."

**Comment by brnvogel** [comment]
Closed in error

**Comment by nsantacruz** [comment]
We have removed this feature because it is difficult to maintain now that we've moved to a new app architecture. We may decide to reinclude this feature in the future but as of now we have no plans. You are welcome make a pull request to add this feature. We can assist you with where to start if you're interested

**Comment by brnvogel** [comment]
Update received.
Cannot understand why a feature that was working has been removed without intention to restore it.
There are a lot of people using Chromebooks and need the ability to work offline.
At least add it to the ''wishlist''
