### ISSUE TITLE
Need ability to "Unselect All" in Search

### ISSUE THREAD

**Issue by chaimkut** [Sefaria/Sefaria-Project#473]
I would like to search for a word inside of a single book. Let's say, searching for "רחל" inside of רות.

Firstly, there only exists the ability to search all texts and only then the user is allowed to filter. Perhaps there should be an "advanced search" option which allows the user to search only within specific texts.

Secondly, after searching all texts, it is difficult to reduce the filter to a single book. The user can narrow to a specific set of books ("תנ"ך"), but narrowing to a specific book requires individually deselecting all other books. There should be a "deselect all" which makes it easier to narrow down the displayed results.

Thirdly, it seems that the search is being performed repeatedly upon each change of the filter? The search should only re-search if new books are *added*, but if the user is simply narrowing down their search, the search should not be resubmitted.

![Screencast of Rachel search](https://i.imgur.com/Hf05xCE.gif)

**Comment by EliezerIsrael** [comment]
Thanks for writing. 

If you want a specific book - click on the *title* of the category, rather than the checkbox next to it.  
That will open up the list of books without selecting them.  then you can select the book you like. 

As for selecting before search, we have the idea on our design radar.

As to multiple searches - we decided that the current method was an acceptable tradeoff in exchange for the the added simplicity of the user-side code.
