### ISSUE TITLE
Calendar API: Incorrect Parashat Hashavua

### ISSUE THREAD

**Issue by matansaar5** [Sefaria/Sefaria-Project#557]
Hi and thanks for your wonderful system.
I would like to report that the calendar API not always return the correct Parasha. for example this week the Parasha is נשא but I get "שבועות ב".
Link: https://www.sefaria.org/api/calendars?timezone=Asia/Jerusalem&day=24&month=05&year=2020

Additionally in your site https://www.sefaria.org/texts when I click on the "Parashat Hashavua" some time it direct me to Deuteronomy 14:22 instead of Numbers.4.21

Thanks

**Comment by edamboritz** [comment]
Hi, please add `&diaspora=0` to the end of that API url to see the Israel centric calendar. 

The website generally responds to your location to give you the correct calendar but I can see there's an occasional bug that takes you to the wrong Parasha link. For now a simple refresh of the page should solve it but we will look into it. 
Thank you for reporting.

**Comment by matansaar5** [comment]
Thanks.

**Comment by ronshapiro** [comment]
Thoughts on returning both the Israel and Diaspora calendars in the same
response (maybe each as a separate maps, or having a field on each value?)

Not knowing to specify this parameter seems like a gotcha.

בתאריך יום א׳, 24 במאי 2020, 14:05, מאת matansaar5 ‏<
notifications@github.com>:

**Comment by edamboritz** [comment]
Hi Ron! 
Yeah, I suppose one can debate the theoretical merits of either approach- 
Either expecting the client to specify parameters on the API that customize the response as needed or returning all bulk data and expecting the client to know what pieces of the response to process and which to disregard based on similar parameters. 

In any case these parameters are all listed in the documentation. 

(To anyone not familiar coming across this issue, I'll point to our API documentation where we strive to keep an up to date usage guide to our main API endpoints. 
https://github.com/Sefaria/Sefaria-Project/wiki/API-Documentation#calendar-api )

**Comment by ronshapiro** [comment]
Yep, for sure. My thought process was that it's all a small amount of data,
so by returning it all, the options are self documenting.

Another reason is that then you don't have to worry about potentially
ambiguous defaults. Jews in Israel vs. in the Diaspora are roughly 50/50,
for example. Because many weeks of the year, Parshat Hashavua is the same
in Israel and in the Diaspora, it's easy to overlook the documentation if
you have something that seemingly works when it's first configured, but
later the two diverge.
