### ISSUE TITLE
Daf Yomi display value in /api/calendars changed to a strange format

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#621]
Here's what I'm seeing as of yesterday:

```json
{
  "title": {
    "en": "Daf Yomi",
    "he": "דף יומי"
  },
  "displayValue": {
    "en": "Pesachim 70a-70",
    "he": "פסחים ע׳ א-ע׳"
  },
  "url": "Pesachim.70a-70b",
  "ref": "Pesachim 70a-70b",
  "order": 3,
  "category": "Talmud"
}
```

The `displayValue` property used to just have "Pesachim 70" in English and "פסחים ע׳" in Hebrew. Now it's a range with the first amud of the daf, and the end of the range is the full daf, which is weird.

The `url` and `ref` properties have the correct values.

**Comment by nsantacruz** [comment]
Thanks! This is a bug due to a recent bug fix actually. It used to be `Ref("Pesachim 2")` would parse as `Ref("Pesachim 2a")` which isn't right. A recent fix was pushed so that it equals `Ref("Pesachim 2a-2b")`.

However, this caused some issues for places that relied on the faulty functionality. I'm pushed a fix in https://github.com/Sefaria/Sefaria-Project/commit/a1907f574506c2c2c91d1b3f0dd9d84780859a03 and hope it gets deployed soon

**Comment by nsantacruz** [comment]
@ronshapiro the fix is now live. closing the issue but feel free to comment if you're still having issues

**Comment by ronshapiro** [comment]
Looks great - thanks!
