### ISSUE TITLE
citing a source

### ISSUE THREAD

**Issue by dalgaze** [Sefaria/Sefaria-Project#627]
when selecting a quote from Talmud, when going for instance from 23b to 24a why do we have to go through the menu again? Why not stay on the same source and select the next page until we want to get out to another source.

**Comment by blockspeiser** [comment]
Could you help us with some more detail about where in the product you're having this problem? Where exactly are you, what are you trying to do, which menu do you mean? 

My best guess is that you are building a source sheet and clicking the button that says "Browse Sources" to select a piece of Talmud to add? If that is the case, inside that menu, when you see the text of the Daf appear, you can click and drag the text (like you were highlighting text) across different pieces of text so that you can add a single source that spans across 23b and 24a.

**Comment by dalgaze** [comment]
Thanks. I’ll try that

**Comment by dalgaze** [comment]
I don’t recall exactly when, bur a dialog box appeared saying error, save your work etc. This is not the first time it happened. At that time the save button on the site was not visible.
