### ISSUE TITLE
Feature Request: Vowel/Trop support in search

### ISSUE THREAD

**Issue by freilich-am** [Sefaria/Sefaria-Project#686]
Hi! I was looking into what it would take to make this happen and was curious if it was even possible.

I was recently trying to find if the word אדונַי with a patach (i.e. my masters) is attested anywhere.
Searching for this, even with "exact search" on gives many many results of the proper name (with a kamatz), even when it's spelled like the shem havaya, and even a few אֲדוֹנִיs. [Random tangents: is there a way to describe to an end user what difference it makes if exact search is on, without resorting to elasticsearch tokenizers? also, in this kind of scenario is there at least a way to only search texts with nikkud?]

Anyway, my understanding is that the main obstacle is elasticsearch. Is that right? Are there other obstacles to this?

(Another thing I was looking for was words ending in ךָּ like וִיחֻנֶּךָּ or, according to ashkenazi siddurim at least sometimes, אַשְׂבִּיעֶֽךָּ. For a trop use case, generally finding pausal forms, finding a word like באה just in the present/past tense. This has weirdly come up alot for me. Another potential use case that would be hard to put in a UI: looking for "word shapes" i.e. יֶדְכֶם 2nd person possessive nouns that get that segol in front. Or even like, searching if the following trop ever appear in this order ever.)

Thanks for reading!

**Comment by rneiss** [comment]
I'm going to close this because I don't think we're going to put it on our roadmap anytime soon, but you might want to check out the code that Noah Liebman mocked up a bunch of years ago here: https://github.com/Noleli/trop-analysis and the corresponding blog post: https://noahliebman.net/2015/04/quantified-cantillation/ which seems to capture a lot of what you're looking at.

Additionally grabbing the text from the [Sefaria-Data](https://github.com/Sefaria/Sefaria-Data/) repo and running some code on that to search and parse will probably be way more efficient than using elastic search for this kind of search. Happy to help get you started on there if you need some additional assistance.
