### ISSUE TITLE
/api/texts spanning refs bug

### ISSUE THREAD

**Issue by ronshapiro** [Sefaria/Sefaria-Project#726]
[`/api/texts/Jerusalem_Talmud_Shekalim.1.1.35-2.13`](https://www.sefaria.org/api/texts/Jerusalem_Talmud_Shekalim.1.1.35-2.13) used to return two elements in the `spanningRefs` field:  `["Jerusalem Talmud Shekalim 1:1:35-50", "Jerusalem Talmud Shekalim 1:2:1-13"]`, but it now is returning just the second.

Was there a change that affected this calculation?

**Comment by ronshapiro** [comment]
Perhaps one of these?

https://github.com/Sefaria/Sefaria-Project/commit/1ce20d24fc2fa585b11c55852700d60b376ec436
https://github.com/Sefaria/Sefaria-Project/commit/1362d5fd38c72a0e0bc07359c54c23abd2200b7b

https://github.com/Sefaria/Sefaria-Project/commit/7a32e0a164b93bfc485c6343cb962cf3aff6472c
https://github.com/Sefaria/Sefaria-Project/commit/d7f200c619dbc5367d1d92b1d875c8ff68a9dd95

**Comment by nsantacruz** [comment]
@ronshapiro the structure of Yerushalmi Shekalim has changed since we launched the Yerushalmi in English. Inspecting that ref, there is no content for Jerusalem Talmud 1:1:35 (1:1 ends at segment 16) so the spanning ref starts at 1:2:1.

We apologize for not better redirecting old refs to new refs. We are currently working on patching this issue so that old refs will still the proper content (that being said, our strategy to deal with this relies on the fact that our old Yerushalmi was structured using vilna dapim so we can easily tell when someone is requesting an old Yerushalmi ref. This isn't true for Shekalim which was already using the new Perek/Halacha format when we launched.
