### ISSUE TITLE
Tractate Makkot and other tractates of Talmud Bavli download does not have tags.

### ISSUE THREAD

**Issue by JamesRead5737** [Sefaria/Sefaria-Project#866]
See for example the download from

https://www.sefaria.org/Makkot

I select 'William Davidson Edition - Aramaic' and 'Text (with Tags)' and download and the download comes in plain text without tags. While if I access the page on the website the text is clearly tagged.

**Comment by nsantacruz** [comment]
Can you give an example of a tag that appears in Makkot but not in the download?

**Comment by JamesRead5737** [comment]
You can start with the very first Daf ב׳ א On the website the word כיצד  (the second word of the text) is obviously tagged as it displays in bold. But in the download it is not tagged.

**Comment by nsantacruz** [comment]
I see what the issue is. The default version for Makkot is "Wikisource Talmud Bavli" which has tags in it. The "William Davidson Edition - Aramaic" version does not have tags in it. 

I realize it is a bit surprising that the William Davidson Edition is not the default across all of Bavli. The current state is a little complicated. We prefer the Wikisource version over William Davidson without vocalization since Wikisource has inline citations. But Dicta is adding vocalization to the William Davidson edition, so when we have vocalization, we prefer the William Davidson edition. We plan to have a fully vocalized version of Bavli by the end of the summer and then the versions will be standard across all mesekhtot.
