### ISSUE TITLE
Mixed language text versions when calling the API vs. URL

### ISSUE THREAD

**Issue by dakoller** [Sefaria/Sefaria-Project#996]
I take the ref & url parameters from the /api/calendars information in order to produce a daily read-out version of the texts.

When calling https://www.sefaria.org/api/texts/Mishneh_Torah,_Murderer_and_the_Preservation_of_Life.11?vDE=_ I get a mixed language version, with some sentences in english and others in german.

When looking at the same information at https://www.sefaria.org/Mishneh_Torah%2C_Murderer_and_the_Preservation_of_Life.10.8?lang=bi I get german text output (as requested).

**Comment by edamboritz** [comment]
Hello, 
Unfortunately the `vDE` url parameter you are using is meaningless, asides from the fact that there is no value attached to it, it's not recognized as a valid input for that API call by our API at all and is therefore ignored. What you wind up getting is a merged "English" version of the text, which is its default state as our English text there is incomplete. The German is incidental as it counts (for legacy reasons when we only had English and Hebrew/Aramaic) as an "English" version. 

In order to get only a specific version you must specify so in the url parameters like so:
https://www.sefaria.org/api/texts/Mishneh_Torah,_Murderer_and_the_Preservation_of_Life.11?ven=Jad_Haghasakkah,_trans._by_L._Mandelstamm._St._Petersburg,_1851._Corrected_and_edited_by_Igor_Itkin_-_German_[de]

or if you dont know the version in advance like so: 
https://www.sefaria.org/api/texts/Mishneh_Torah,_Murderer_and_the_Preservation_of_Life.11?transLangPref=de 
(Though this second option doesnt guarantee the language, if it does not exist for the text)

Note that generally LTR languages will be "English" and therefore used in the `ven` url param, and RTL will be `vhe` for the "Hebrew" versions. 

On the site itself, you might have been getting the German correctly because we saved you preferences via cookie when you selected that version the first time. 

As our multilingual corpus grows, we aim to also improve the functionality surrounding multi lingual translations.

**Comment by dakoller** [comment]
@edamboritz many thanks for the explanation!
